find_path(CANLIB_INCLUDE_DIR
    NAMES canlib.h
    PATHS ${CMAKE_SOURCE_DIR}/canlib/inc
)

SET(CMAKE_FIND_LIBRARY_PREFIXES "lib")
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".lib" ".dll" ".a")
find_library(CANLIB_LIBRARY
    NAMES canlib32.lib
    PATHS ${CMAKE_SOURCE_DIR}/canlib/lib
)

message(CANLIB_INCLUDE_DIR: ${CANLIB_INCLUDE_DIR})
message(CANLIB_LIBRARY: ${CANLIB_LIBRARY})


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(canlib DEFAULT_MSG CANLIB_LIBRARY CANLIB_INCLUDE_DIR)

MARK_AS_ADVANCED(CANLIB_INCLUDE_DIR CANLIB_LIBRARY)